### ISSUE TITLE
Questions about the elsa loss

### ISSUE THREAD

**Issue by cxmscb** [archon159/elsa#1]
Thanks for the great work.
I am confused about the loss (13) minimization, where minimizing 1/S(x) could cause S(x) to be negative rather than to be larger? It seems that S(x) could be negative based on the equation (12).

**Comment by Sungwon-Han** [comment]
Thank you for raising this question. As you said, S(x) can be negative according to the definition.
However, S(x) rarely becomes negative in the actual cases, especially if we set the number of prototypes to at least 8.
Given the temperature $\tau=0.5$ and the number of prototypes $N$, the score $S(x)$ is bounded as follows: $S(x) \geq \log (N \times e^{-2})$, as cosine similarity lies within the range [-1, 1]. If $N \geq 8$, $S(x)$ becomes always positive, and thereby the aforementioned issue does not occur.

**Comment by cxmscb** [comment]
Thanks for your detail reply. Since the N I used is small, how about revising the cosine similarity to the equation (cosine similarity + 1)/2 in the traning?

**Comment by Sungwon-Han** [comment]
I think it would be also fine!
